name: r-2021-sarscov2-inzidenzen
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - conda-forge::r-tidyverse
  - conda-forge::r-base
  - conda-forge::r-plotly
  - conda-forge::r-knitr
  - conda-forge::r-ggrepel
  - conda-forge::r-curl
  - conda-forge::r-readxl
  - conda-forge::r-shiny
  - conda-forge::r-shinycssloaders
  - conda-forge::r-shinydashboard
